### ISSUE TITLE
Point Cloud Plugin Release Checklist

### ISSUE THREAD

**Issue by ritch** [voxel51/fiftyone-plugins#1]
## Features

**Rendering point cloud data stored in .pcd format**

 - [ ] allow user to specify orientation of lidar (similar to orientation of camera)
 - [ ] use filepath as the source for pcd data by default, allow override for advanced use cases

**Coloring point clouds by intensity or z-value using a configurable colorscale**

 - [x] color by z value
 - [ ] color by intensity
 - [ ] configurable colorscale

**Rendering 3D detections and polylines stored in FiftyOne’s default 3D Label types**

 - [ ] remove support for 2d types + additional 3d data
 - [ ] add support for new 3D Detection types
 - [ ] improve polygon support

**Perspective camera model (pinhole) with support for position/rotation/zoom adjustments**

 - [x] allow for customizing initial position

**Support for mapping App field colors onto objects in the scene**

 - [ ] use existing colorscales (requires new @fiftyone/state module)

**Support for filtering objects in the scene via the App’s filters**

 - [x] inherit state from app + render what matches app filters

**Support for selecting and tagging objects in the scene**

 - [x] support label selection
 - [x] support label clearing
 - [ ] fix label tagging

## Publishing

 - [ ] setup npm team/org
 - [ ] publish initial version / release candidate for install testing
 - [ ] publish v1.0.0

## Docs

 - [ ] install instructions
 - [ ] settings
